name: smtptest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.24"
          - "1.25"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Test
      run: |
        go test ./...

  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Tag repo with version
      env:
        VERSION: v1.0.0
      run: |
        export VERSION_TAG=$VERSION-$(date +%s%3N)
        git tag $VERSION_TAG
        git push --tags
      if: ${{ success() && github.ref == 'refs/heads/main' }}
