name: smtptest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      VERSION: v1.0.0
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.24"
          - "1.25"
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Install tools
      run: go install gotest.tools/gotestsum@latest

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Test
      run: |
        gotestsum ./...

    - name: Tag Build
      env:
          GITHUB_TOKEN: ${{ github.token }}
      run: |
        export VERSION_TAG=$VERSION-$(date +%s%3N)
        git tag $VERSION_TAG
        git push --tags
      if: ${{ success() && github.ref == 'refs/heads/main' }}
